import type { Metadata } from "next";
import {  Poppins, Roboto } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "./sections/Header"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100","200","400", "500", "600", "700"],
  variable: "--font-roboto",
  display: "swap",
});
const aghraham = localFont({
  src: "./fonts/Agraham.otf",
  variable: "--font-aghraham",
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${aghraham.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}</body>
    </html>
  );
}
